openapi: 3.0.1
info:
  title: Khanmigo
  description: An endpoint to get a list of tutorials to educate the user on an educational topic if the user keeps asking questions related to the same topic. 
  version: 0.1.0
servers:
  - url: https://www.khanacademy.org/api/internal/_rg/khanmigo
paths:
  /search_content:
    get: {
      tags: 
       - khanmigo-tutorials-endpoint
      summary: API for fetching khanacademy tutorials list
      operationId: getTutorialsList
      description: Endpoint to query for tutorials.
      parameters:
        - name: query
          in: query
          description: The topic, for which we need the list of tutorials, is passed in this parameter (example: astronomy, math, logarithms, marinebiology).
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
