openapi: 3.0.1
info:
  title: Khanmigo
  description: A plugin that is an AI powered tutor that uses material from the reputable and trusted source of Khan Academy. Khanmigo is trustworthy, provides continuity across the learning journey, and provides embedded Khan Academy content. 
  version: 0.1.0
servers:
  - url: https://www.khanacademy.org/api/internal/_rg/khanmigo
paths:
  /search_content:
    get:
      operationId: getTutorial
      description: Gets the probable tutorial given the subject matter.
      parameters:
        - name: query
          in: query
          description: The subject being searched for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    description:
                      type: string
                      description: A brief overview of the content.
                    kind:
                      type: string
                      description: The type of content (e.g., Course, Article, Video).
                    title:
                      type: string
                      description: The title of the content.
                    url:
                      type: string
                      format: uri
                      description: The URL to access the content.
              example:
                - description: "It's a great, big universe out there..."
                  kind: Course
                  title: Cosmology and astronomy
                  url: https://khanacademy.org/science/cosmology-and-astronomy
                - kind: Article
                  title: Simulations in astronomy
                  url: https://khanacademy.org/computing/ap-computer-science-principles/x2d2f703b37b450a3:simulations/x2d2f703b37b450a3:exploring-simulations/a/astronomy-simulations
                - kind: Video
                  title: Neutrino astronomy: a new frontier
                  url: https://khanacademy.org/college-careers-more/bjc/2019-challenge/2019-challenge-finalists/v/neutrino-astronomy-a-new-frontier
                - kind: Video
                  title: Detectable civilizations in our galaxy 4
                  url: https://khanacademy.org/science/cosmology-and-astronomy/life-earth-universe/life-in-universe-topic/v/detectable-civilizations-in-our-galaxy-4
